1. vite  프로젝트 생성  (VS)
https://ko.vite.dev/guide/

npm create vite@latest my-app  (react , javascript 선택)

 cd my-app
 npm install
 npm run dev

웹사이트에서 확인 : http://localhost:5173/

--------------------------------------------------------------------------
2. github  저장소 생성
2.1 배포 주소확인
https://github.com/kglim1004/my-app.git

제공하는 script
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/kglim1004/my-app.git
git push -u origin main


3. 프로젝트 폴더 에서
git init
git remote add origin https://github.com/kglim1004/....
git add .           (새로만든파일  , 수정된 파일)
​or git add --all   (새로만든 파일 , 수정된 파일 , 삭제된 파일)
gitt commit -m "init"
​git push -u origin master


4. github 확인
https://github.com/kglim1004/my-app/settings/pages
Build and deployment  >> Github Actions  > CI & CD

5. 
# GitHub Pages를 통해 정적 콘텐츠를 배포하는 간단한 워크플로우
name: Deploy static content to Pages

on:
  # 기본 브랜치에 대한 푸시 이벤트 발생 시 실행
  push:
    branches: ['master']

  # Actions 탭에서 수동으로 워크플로우를 실행할 수 있도록 구성
  workflow_dispatch:

# GITHUB_TOKEN의 권한을 설정하여 GitHub Pages에 배포할 수 있도록 함
permissions:
  contents: read
  pages: write
  id-token: write

# 동시에 하나의 배포만 허용하도록 구성
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # 단순히 배포만 수행하기에 하나의 잡으로만 구성
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # dist 폴더 업로드
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4